//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;


using LinqToDB;
using LinqToDB.Mapping;

namespace IdeaMarket.DataModel
{
	/// <summary>
	/// Database       : postgres
	/// Data Source    : 127.0.0.1
	/// Server Version : 9.6.1
	/// </summary>
	public partial class MainDB : LinqToDB.Data.DataConnection
	{
		public MainDB()
			: base("MainDb")
		{
			InitDataContext();
		}

		public MainDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}
}
